server_names = ['cloudflare']
listen_addresses = ['127.0.0.1:5366']
max_clients = 250
ipv4_servers = true
ipv6_servers = true
force_tcp = false
proxy = 'socks5://127.0.0.1:1080'
# http_proxy = 'http://127.0.0.1:8888'
timeout = 5000
keepalive = 30
lb_strategy = 'p2'
lb_estimator = true
cert_refresh_delay = 240
fallback_resolver = '9.9.9.9:53'
ignore_system_dns = true
netprobe_timeout = 60
netprobe_address = '9.9.9.9:53'
log_files_max_age = 1
log_files_max_backups = 1
block_ipv6 = false
cache = true
cache_size = 1024
cache_min_ttl = 1800
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

[query_log]
  format = 'tsv'

[nx_log]
  format = 'tsv'

[blacklist]

[ip_blacklist]

[whitelist]

[schedules]

[sources]
[sources.public-resolvers]
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  prefix = ''

[static]
